### ISSUE TITLE
implementation in OpenRGB ?

### ISSUE THREAD

**Issue by kinooyume** [daniel5151/fusion-kbd-controller-rs#1]
Hey, thank's for your work :) 
Did you consider implementing aero 15X keyboard support to [openRGB](https://gitlab.com/CalcProgrammer1/OpenRGB ) ? 
It had a pretty decent GUI and windows/linux compatibility..
Just a proposition :)

**Comment by daniel5151** [comment]
Hey, glad you found this little utility useful!

As you can tell by the commit history, I haven't touched this project for a while now. While I was aware of things like Aurora and openRGB when working on this utility, I decided against integrating with those projects since it seemed like a lot of effort, and I just needed something basic for my own needs.

I don't have any plans to revisit this project any time soon, but there's no reason why someone couldn't use the code in this repo as a starting point to integrate with openRGB.

**Comment by kinooyume** [comment]
Got it, thank's for your answer :)
